# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Request

class MessageType(object):
    NONE = 0
    Login = 1
    Register = 2
    GetMe = 3
    EditMe = 4
    RequestContract = 5
    ListContracts = 6
    CheckContract = 7

