// automatically generated by the FlatBuffers compiler, do not modify

package online.mctf.tomtom.api.models.Response;

public final class MessageType {
	public static final byte NONE = 0;
	public static final byte Login = 1;
	public static final byte Register = 2;
	public static final byte GetMe = 3;
	public static final byte EditMe = 4;
	public static final byte RequestContract = 5;
	public static final byte ListContracts = 6;
	public static final byte CheckContract = 7;
	public static final String[] names = {"NONE", "Login", "Register", "GetMe", "EditMe", "RequestContract", "ListContracts", "CheckContract",};

	private MessageType() {
	}

	public static String name(int e) {
		return names[e];
	}
}

