// automatically generated by the FlatBuffers compiler, do not modify

package online.mctf.tomtom.api.models.Response;

import androidx.annotation.Nullable;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Message extends Table {
	public static Message getRootAsMessage(ByteBuffer _bb) {
		return getRootAsMessage(_bb, new Message());
	}

	public static Message getRootAsMessage(ByteBuffer _bb, Message obj) {
		_bb.order(ByteOrder.LITTLE_ENDIAN);
		return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
	}

	public static int createMessage(FlatBufferBuilder builder,
									byte msg_type,
									int msgOffset,
									boolean error,
									int errorDescriptionOffset) {
		builder.startObject(4);
		Message.addErrorDescription(builder, errorDescriptionOffset);
		Message.addMsg(builder, msgOffset);
		Message.addError(builder, error);
		Message.addMsgType(builder, msg_type);
		return Message.endMessage(builder);
	}

	public static void startMessage(FlatBufferBuilder builder) {
		builder.startObject(4);
	}

	public static void addMsgType(FlatBufferBuilder builder, byte msgType) {
		builder.addByte(0, msgType, 0);
	}

	public static void addMsg(FlatBufferBuilder builder, int msgOffset) {
		builder.addOffset(1, msgOffset, 0);
	}

	public static void addError(FlatBufferBuilder builder, boolean error) {
		builder.addBoolean(2, error, false);
	}

	public static void addErrorDescription(FlatBufferBuilder builder, int errorDescriptionOffset) {
		builder.addOffset(3, errorDescriptionOffset, 0);
	}

	public static int endMessage(FlatBufferBuilder builder) {
		int o = builder.endObject();
		return o;
	}

	public static void finishMessageBuffer(FlatBufferBuilder builder, int offset) {
		builder.finish(offset);
	}

	public static void finishSizePrefixedMessageBuffer(FlatBufferBuilder builder, int offset) {
		builder.finishSizePrefixed(offset);
	}

	public void __init(int _i, ByteBuffer _bb) {
		bb_pos = _i;
		bb = _bb;
		vtable_start = bb_pos - bb.getInt(bb_pos);
		vtable_size = bb.getShort(vtable_start);
	}

	public Message __assign(int _i, ByteBuffer _bb) {
		__init(_i, _bb);
		return this;
	}

	public byte msgType() {
		int o = __offset(4);
		return o != 0 ? bb.get(o + bb_pos) : 0;
	}

	public @Nullable
	Table msg(Table obj) {
		int o = __offset(6);
		return o != 0 ? __union(obj, o) : null;
	}

	public boolean error() {
		int o = __offset(8);
		return o != 0 && 0 != bb.get(o + bb_pos);
	}

	public @Nullable
	String errorDescription() {
		int o = __offset(10);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer errorDescriptionAsByteBuffer() {
		return __vector_as_bytebuffer(10, 1);
	}

	public ByteBuffer errorDescriptionInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 10, 1);
	}
}

