// automatically generated by the FlatBuffers compiler, do not modify

package online.mctf.tomtom.api.models.Response;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class User extends Table {
	public static User getRootAsUser(ByteBuffer _bb) {
		return getRootAsUser(_bb, new User());
	}

	public static User getRootAsUser(ByteBuffer _bb, User obj) {
		_bb.order(ByteOrder.LITTLE_ENDIAN);
		return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
	}

	public static int createUser(FlatBufferBuilder builder,
								 int usernameOffset,
								 int firstNameOffset,
								 int lastNameOffset) {
		builder.startObject(3);
		User.addLastName(builder, lastNameOffset);
		User.addFirstName(builder, firstNameOffset);
		User.addUsername(builder, usernameOffset);
		return User.endUser(builder);
	}

	public static void startUser(FlatBufferBuilder builder) {
		builder.startObject(3);
	}

	public static void addUsername(FlatBufferBuilder builder, int usernameOffset) {
		builder.addOffset(0, usernameOffset, 0);
	}

	public static void addFirstName(FlatBufferBuilder builder, int firstNameOffset) {
		builder.addOffset(1, firstNameOffset, 0);
	}

	public static void addLastName(FlatBufferBuilder builder, int lastNameOffset) {
		builder.addOffset(2, lastNameOffset, 0);
	}

	public static int endUser(FlatBufferBuilder builder) {
		int o = builder.endObject();
		builder.required(o, 4);  // username
		builder.required(o, 6);  // firstName
		builder.required(o, 8);  // lastName
		return o;
	}

	public void __init(int _i, ByteBuffer _bb) {
		bb_pos = _i;
		bb = _bb;
		vtable_start = bb_pos - bb.getInt(bb_pos);
		vtable_size = bb.getShort(vtable_start);
	}

	public User __assign(int _i, ByteBuffer _bb) {
		__init(_i, _bb);
		return this;
	}

	public String username() {
		int o = __offset(4);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer usernameAsByteBuffer() {
		return __vector_as_bytebuffer(4, 1);
	}

	public ByteBuffer usernameInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 4, 1);
	}

	public String firstName() {
		int o = __offset(6);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer firstNameAsByteBuffer() {
		return __vector_as_bytebuffer(6, 1);
	}

	public ByteBuffer firstNameInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 6, 1);
	}

	public String lastName() {
		int o = __offset(8);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer lastNameAsByteBuffer() {
		return __vector_as_bytebuffer(8, 1);
	}

	public ByteBuffer lastNameInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 8, 1);
	}
}

