# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Request

import flatbuffers

class GetMe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetMe(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetMe()
        x.Init(buf, n + offset)
        return x

    # GetMe
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetMe
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GetMeStart(builder): builder.StartObject(1)
def GetMeAddToken(builder, token): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)
def GetMeEnd(builder): return builder.EndObject()
