# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Request

import flatbuffers

class Login(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLogin(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Login()
        x.Init(buf, n + offset)
        return x

    # Login
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Login
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Login
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LoginStart(builder): builder.StartObject(2)
def LoginAddUsername(builder, username): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)
def LoginAddPassword(builder, password): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)
def LoginEnd(builder): return builder.EndObject()
