// automatically generated by the FlatBuffers compiler, do not modify

package online.mctf.tomtom.api.models.Request;

import androidx.annotation.Nullable;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EditMe extends Table {
	public static EditMe getRootAsEditMe(ByteBuffer _bb) {
		return getRootAsEditMe(_bb, new EditMe());
	}

	public static EditMe getRootAsEditMe(ByteBuffer _bb, EditMe obj) {
		_bb.order(ByteOrder.LITTLE_ENDIAN);
		return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
	}

	public static int createEditMe(FlatBufferBuilder builder,
								   int usernameOffset,
								   int passwordOffset,
								   int firstNameOffset,
								   int lastNameOffset,
								   boolean admin,
								   int tokenOffset) {
		builder.startObject(6);
		EditMe.addToken(builder, tokenOffset);
		EditMe.addLastName(builder, lastNameOffset);
		EditMe.addFirstName(builder, firstNameOffset);
		EditMe.addPassword(builder, passwordOffset);
		EditMe.addUsername(builder, usernameOffset);
		EditMe.addAdmin(builder, admin);
		return EditMe.endEditMe(builder);
	}

	public static void startEditMe(FlatBufferBuilder builder) {
		builder.startObject(6);
	}

	public static void addUsername(FlatBufferBuilder builder, int usernameOffset) {
		builder.addOffset(0, usernameOffset, 0);
	}

	public static void addPassword(FlatBufferBuilder builder, int passwordOffset) {
		builder.addOffset(1, passwordOffset, 0);
	}

	public static void addFirstName(FlatBufferBuilder builder, int firstNameOffset) {
		builder.addOffset(2, firstNameOffset, 0);
	}

	public static void addLastName(FlatBufferBuilder builder, int lastNameOffset) {
		builder.addOffset(3, lastNameOffset, 0);
	}

	public static void addAdmin(FlatBufferBuilder builder, boolean admin) {
		builder.addBoolean(4, admin, false);
	}

	public static void addToken(FlatBufferBuilder builder, int tokenOffset) {
		builder.addOffset(5, tokenOffset, 0);
	}

	public static int endEditMe(FlatBufferBuilder builder) {
		int o = builder.endObject();
		builder.required(o, 14);  // token
		return o;
	}

	public void __init(int _i, ByteBuffer _bb) {
		bb_pos = _i;
		bb = _bb;
		vtable_start = bb_pos - bb.getInt(bb_pos);
		vtable_size = bb.getShort(vtable_start);
	}

	public EditMe __assign(int _i, ByteBuffer _bb) {
		__init(_i, _bb);
		return this;
	}

	public @Nullable
	String username() {
		int o = __offset(4);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer usernameAsByteBuffer() {
		return __vector_as_bytebuffer(4, 1);
	}

	public ByteBuffer usernameInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 4, 1);
	}

	public @Nullable
	String password() {
		int o = __offset(6);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer passwordAsByteBuffer() {
		return __vector_as_bytebuffer(6, 1);
	}

	public ByteBuffer passwordInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 6, 1);
	}

	public @Nullable
	String firstName() {
		int o = __offset(8);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer firstNameAsByteBuffer() {
		return __vector_as_bytebuffer(8, 1);
	}

	public ByteBuffer firstNameInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 8, 1);
	}

	public @Nullable
	String lastName() {
		int o = __offset(10);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer lastNameAsByteBuffer() {
		return __vector_as_bytebuffer(10, 1);
	}

	public ByteBuffer lastNameInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 10, 1);
	}

	public boolean admin() {
		int o = __offset(12);
		return o != 0 && 0 != bb.get(o + bb_pos);
	}

	public String token() {
		int o = __offset(14);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer tokenAsByteBuffer() {
		return __vector_as_bytebuffer(14, 1);
	}

	public ByteBuffer tokenInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 14, 1);
	}
}

