// automatically generated by the FlatBuffers compiler, do not modify

package online.mctf.tomtom.api.models.Request;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Login extends Table {
	public static Login getRootAsLogin(ByteBuffer _bb) {
		return getRootAsLogin(_bb, new Login());
	}

	public static Login getRootAsLogin(ByteBuffer _bb, Login obj) {
		_bb.order(ByteOrder.LITTLE_ENDIAN);
		return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
	}

	public static int createLogin(FlatBufferBuilder builder,
								  int usernameOffset,
								  int passwordOffset) {
		builder.startObject(2);
		Login.addPassword(builder, passwordOffset);
		Login.addUsername(builder, usernameOffset);
		return Login.endLogin(builder);
	}

	public static void startLogin(FlatBufferBuilder builder) {
		builder.startObject(2);
	}

	public static void addUsername(FlatBufferBuilder builder, int usernameOffset) {
		builder.addOffset(0, usernameOffset, 0);
	}

	public static void addPassword(FlatBufferBuilder builder, int passwordOffset) {
		builder.addOffset(1, passwordOffset, 0);
	}

	public static int endLogin(FlatBufferBuilder builder) {
		int o = builder.endObject();
		builder.required(o, 4);  // username
		builder.required(o, 6);  // password
		return o;
	}

	public void __init(int _i, ByteBuffer _bb) {
		bb_pos = _i;
		bb = _bb;
		vtable_start = bb_pos - bb.getInt(bb_pos);
		vtable_size = bb.getShort(vtable_start);
	}

	public Login __assign(int _i, ByteBuffer _bb) {
		__init(_i, _bb);
		return this;
	}

	public String username() {
		int o = __offset(4);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer usernameAsByteBuffer() {
		return __vector_as_bytebuffer(4, 1);
	}

	public ByteBuffer usernameInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 4, 1);
	}

	public String password() {
		int o = __offset(6);
		return o != 0 ? __string(o + bb_pos) : null;
	}

	public ByteBuffer passwordAsByteBuffer() {
		return __vector_as_bytebuffer(6, 1);
	}

	public ByteBuffer passwordInByteBuffer(ByteBuffer _bb) {
		return __vector_in_bytebuffer(_bb, 6, 1);
	}
}

