// automatically generated by the FlatBuffers compiler, do not modify

package online.mctf.tomtom.api.models.Request;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Message extends Table {
	public static Message getRootAsMessage(ByteBuffer _bb) {
		return getRootAsMessage(_bb, new Message());
	}

	public static Message getRootAsMessage(ByteBuffer _bb, Message obj) {
		_bb.order(ByteOrder.LITTLE_ENDIAN);
		return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
	}

	public static int createMessage(FlatBufferBuilder builder,
									byte msg_type,
									int msgOffset) {
		builder.startObject(2);
		Message.addMsg(builder, msgOffset);
		Message.addMsgType(builder, msg_type);
		return Message.endMessage(builder);
	}

	public static void startMessage(FlatBufferBuilder builder) {
		builder.startObject(2);
	}

	public static void addMsgType(FlatBufferBuilder builder, byte msgType) {
		builder.addByte(0, msgType, 0);
	}

	public static void addMsg(FlatBufferBuilder builder, int msgOffset) {
		builder.addOffset(1, msgOffset, 0);
	}

	public static int endMessage(FlatBufferBuilder builder) {
		int o = builder.endObject();
		builder.required(o, 6);  // msg
		return o;
	}

	public static void finishMessageBuffer(FlatBufferBuilder builder, int offset) {
		builder.finish(offset);
	}

	public static void finishSizePrefixedMessageBuffer(FlatBufferBuilder builder, int offset) {
		builder.finishSizePrefixed(offset);
	}

	public void __init(int _i, ByteBuffer _bb) {
		bb_pos = _i;
		bb = _bb;
		vtable_start = bb_pos - bb.getInt(bb_pos);
		vtable_size = bb.getShort(vtable_start);
	}

	public Message __assign(int _i, ByteBuffer _bb) {
		__init(_i, _bb);
		return this;
	}

	public byte msgType() {
		int o = __offset(4);
		return o != 0 ? bb.get(o + bb_pos) : 0;
	}

	public Table msg(Table obj) {
		int o = __offset(6);
		return o != 0 ? __union(obj, o) : null;
	}
}

