# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Response

import flatbuffers

class EditMe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEditMe(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EditMe()
        x.Init(buf, n + offset)
        return x

    # EditMe
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EditMe
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EditMeStart(builder): builder.StartObject(1)
def EditMeAddToken(builder, token): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)
def EditMeEnd(builder): return builder.EndObject()
