# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Response

import flatbuffers

class GetMe(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetMe(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetMe()
        x.Init(buf, n + offset)
        return x

    # GetMe
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetMe
    def Username(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GetMe
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GetMe
    def FirstName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GetMe
    def LastName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GetMe
    def Admin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GetMeStart(builder): builder.StartObject(5)
def GetMeAddUsername(builder, username): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(username), 0)
def GetMeAddPassword(builder, password): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)
def GetMeAddFirstName(builder, firstName): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(firstName), 0)
def GetMeAddLastName(builder, lastName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(lastName), 0)
def GetMeAddAdmin(builder, admin): builder.PrependBoolSlot(4, admin, 0)
def GetMeEnd(builder): return builder.EndObject()
