# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Response

import flatbuffers

class ListContracts(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsListContracts(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListContracts()
        x.Init(buf, n + offset)
        return x

    # ListContracts
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListContracts
    def Contracts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .CheckContract import CheckContract
            obj = CheckContract()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ListContracts
    def ContractsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ListContractsStart(builder): builder.StartObject(1)
def ListContractsAddContracts(builder, contracts): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(contracts), 0)
def ListContractsStartContractsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ListContractsEnd(builder): return builder.EndObject()
