# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Response

import flatbuffers

class RequestContract(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRequestContract(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestContract()
        x.Init(buf, n + offset)
        return x

    # RequestContract
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestContract
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .CheckContract import CheckContract
            obj = CheckContract()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RequestContractStart(builder): builder.StartObject(1)
def RequestContractAddResult(builder, result): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)
def RequestContractEnd(builder): return builder.EndObject()
